services:
  - type: web
    name: km0-market-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run db:prod && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_ORM
        value: drizzle
    autoDeploy: true
