services:
  - type: web
    name: km0-market-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run db:prod && npm run build:prod
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: CORS_ORIGIN
        value: https://tu-frontend-domain.com
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
