services:
  - type: web
    name: km0-market-backend
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run db:prod && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_ORM
        value: prisma
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: CORS_ORIGIN
        value: https://km0-market.vercel.app
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
